redisson:
  single_server_config:
    idle_connection_timeout: 10000
    connect_timeout: 10000
    timeout: 3000
    retry_attempts: 3
    retry_interval: 1500
    password: null
    subscriptions_per_connection: 5
    client_name: null
    address: "redis://127.0.0.1:6379"
    subscription_connection_minimum_idle_size: 1
    subscription_connection_pool_size: 50
    connection_minimum_idle_size: 24
    connection_pool_size: 64
    database: 0
    dns_monitoring_interval: 5000
  threads: 16
  netty_threads: 32
  transport_mode: "NIO"